### ISSUE TITLE
simpleicons integration not found - 2021.5

### ISSUE THREAD

**Issue by n00bcodr** [vigonotion/hass-simpleicons#112] opened 2021-04-29 11:48 UTC
On HomeAssistant 2021.5.0b1. It just says integration not found.

```
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 5:15:52 PM (1 occurrences)
Last logged: 5:15:52 PM

Setup failed for simpleicons: Integration not found.
```

![image](https://user-images.githubusercontent.com/49611451/116545895-9b980680-a90e-11eb-87ce-162ca250dad2.png)

And in the integrations page, the integration is not loaded, uninstalling it from HACS or deleting the folder from custom components does not do anything.

![image](https://user-images.githubusercontent.com/49611451/116546010-c2eed380-a90e-11eb-96de-238fe21647ad.png)

**Comment by howlermonkeys** [comment] 2021-04-29 11:49
I can confirm, I am having the same problem

**Comment by PrathikGopal** [comment] 2021-04-29 16:57
Same with me!

**Comment by guevara777** [comment] 2021-04-30 04:39
I can confirm, too. Same problem

**Comment by n00bcodr** [comment] 2021-04-30 05:06
I even tried downgrading it, no luck.

**Comment by n00bcodr** [comment] 2021-04-30 05:17
Upgraded to core 2021.5.0b2, could remove simple icons from integrations.

Tried reinstalling it in HACS, it not showing back up in integrations.

**Comment by vigonotion** [comment] 2021-04-30 05:25
Can y'all try manually installing it? Does that work? I'm trying to figure out if this is a problem with hacs or this integration

**Comment by drthanwho** [comment] 2021-04-30 11:51
Even though showing installed in HACS (even after reinstalling) actually no simpleicons folder exists anymore in custom_components. 

Manually adding it and restarting fixes the problem

**Comment by n00bcodr** [comment] 2021-04-30 15:41
I manually copied the folder to custom_components.

I cannot find simpleicons in integrations.

![image](https://user-images.githubusercontent.com/49611451/116718613-c6aa5500-a9f7-11eb-841d-eefa30bd4b05.png)

**Comment by drthanwho** [comment] 2021-04-30 15:44
> I cannot find simpleicons in integrations.
 
Isn't it still added as a card from before?

**Comment by n00bcodr** [comment] 2021-04-30 15:47
@drthanwho nope. I upgraded to beta 2 and I got an option to remove the integration and removed it as it was throwing an error at every restart.

**Comment by drthanwho** [comment] 2021-04-30 15:56
Restarted after you added the folder? If yes then try also deleting cache

**Comment by j6s33m** [comment] 2021-05-03 17:48
This is still a problem for non-beta HA users. See image below. I cannot install manually...it provides config errors every time.

<img width="879" alt="Screen Shot 2021-05-03 at 11 31 11 AM" src="https://user-images.githubusercontent.com/17929290/116904261-17da6480-ac03-11eb-8d07-5e89b620ab04.png">

**Comment by vigonotion** [comment] 2021-05-04 11:53
You can select the v1.17 version in the dropdown

**Comment by j6s33m** [comment] 2021-05-04 12:32
Trying to downgrade versions or manually installing doesn't work either. I've cleared cache and still have same issue.

**Comment by kyotodesertfox** [comment] 2021-05-05 15:54
I noticed when I search for SI on the Home Assistant integration website; and it isn't listed there either.

![Screenshot_20210505-115434](https://user-images.githubusercontent.com/19782272/117171217-afbd8700-ad98-11eb-8abe-f5de3dda4eb3.png)

**Comment by vigonotion** [comment] 2021-05-05 17:28
@kyotodesertfox SI is not an official integration, so you will not find it on the HA website

**Comment by broyuken** [comment] 2021-05-05 21:16
Same issue on the final release of HA.

**Comment by nepozs** [comment] 2021-05-06 01:48
Temporary workaround - manual install (NOTusing HACS):
copy the contents of `custom_components/simpleicons/` to `<your config dir>/custom_components/simpleicons/`.

**Comment by Jozziej** [comment] 2021-05-06 06:52
When I download the simpleicons folder from the Github page, the manifest.json version information says "0.0.0".
This should be "1.8.0".

I installed it through HACS, then copied the folder to the custom_components folder from Github with changing the Manifest.json version to 1.8.0. Restart HA and some refresh of the page afterwards and the icons are back:)

**Comment by vigonotion** [comment] 2021-05-06 07:16
@Jozziej interesting, the github 0.0.0 is intended. The release contains a zip file with the correct manifest (generated automatically). Maybe the zip release is not working correctly with HACS

**Comment by jamieshaw** [comment] 2021-05-06 08:10
Having just installed simpleicons v1.18.1 via HACS — this issue continues to persist.

**Comment by SeLLeRoNe** [comment] 2021-05-06 08:11
I've noticed something different, I tried to remove and re-install, and on re-install it doesn't even create the folder (even tho it say it is installed).

**Comment by SeLLeRoNe** [comment] 2021-05-06 08:14
Also @vigonotion , while I do understand that the source code have 0.0.0 to have then GitHub assign the right version in the manifest, I believe that it is not working because the manifest inside the zip file still say 0.0.0, which lead me to think that that bit isn't working either :)

**Comment by jamieshaw** [comment] 2021-05-06 08:15
> I've noticed something different, I tried to remove and re-install, and on re-install it doesn't even create the folder (even tho it say it is installed).

Huh. Right you are. I did the same, and sure enough, no `simpleicons` folder.

**Comment by SeLLeRoNe** [comment] 2021-05-06 08:20
Another update. I've downloaded the zip from github, extracted and pushed the "simpleicon" folder (that sits inside hass-simpleicon/custom_compoennts) into the custom_compoents folder, but still simpleicon seems not to be working.

Logs reveal:
`021-05-06 10:16:33 ERROR (MainThread) [homeassistant.setup] Error during setup of component simpleicons
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/home/ha/.homeassistant/custom_components/simpleicons/__init__.py", line 29, in async_setup
    register_modules(hass)
  File "/home/ha/.homeassistant/custom_components/simpleicons/__init__.py", line 52, in register_modules
    url_set.discard(ICONS_URL+v)
AttributeError: 'UrlManager' object has no attribute 'discard'
`

**Comment by vigonotion** [comment] 2021-05-06 08:31
Please update to v1.18.3. Should be fixed now

**Closed by vigonotion** 2021-05-06 08:31 UTC

**Comment by SeLLeRoNe** [comment] 2021-05-06 08:33
Confirmed to be working as expected now!

Thanks @vigonotion !

**Comment by ronschaeffer** [comment] 2021-05-06 08:40
Ditto. Now working, Thanks.
